export const CommonConst = {
  backArrow: '←',
  nextArrow: '›',
  unknownUserInitial: 'U',
};

export const AuthConst = {
  loginTitle: 'Sign In',
  loginSubtitle: 'High-precision AI network',
  signupTitle: 'Sign Up',
  signupSubtitle: 'High-precision network',
  continueWithGoogle: 'Continue with Google',
  dividerOr: 'OR',
  emailLabel: 'Email Address',
  emailPlaceholder: 'Enter your email',
  passwordLabel: 'Password',
  passwordPlaceholder: '••••••••',
  signInButton: 'Sign In',
  signUpButton: 'Sign Up',
  loginFooterPrefix: 'New to AIDetect? ',
  loginFooterCta: 'Register now',
  signupNameLabel: 'Full Name',
  signupNamePlaceholder: 'Enter your name',
  signupFooterPrefix: 'Already have an account? ',
  signupFooterCta: 'Sign In',
  verifyOtpTitle: 'Verify OTP',
  verifyOtpSubtitle: "We've sent a code to",
  verifyOtpButton: 'Verify Code',
  otpResendPrefix: "Didn't receive code? ",
  otpResendCta: 'Resend now',
  loginFailedTitle: 'Login Failed',
  tryAgainMessage: 'Please try again.',
  resetEmailRequired: 'Enter your email to reset password',
  resetEmailSentTitle: 'Email Sent',
  resetEmailSentMessage: 'Check your inbox for password reset instructions.',
  genericErrorTitle: 'Error',
  resetEmailFailedMessage: 'Failed to send reset email.',
  signupFailedTitle: 'Signup Failed',
  emailRequiredError: 'Email is required',
  validEmailError: 'Please enter a valid email',
  passwordRequiredError: 'Password is required',
  passwordMinLengthError: 'Password must be at least 6 characters',
  fullNameRequiredError: 'Full name is required',
  passwordUppercaseError: 'Password must contain at least one uppercase letter',
  passwordNumberError: 'Password must contain at least one number',
};

export const HomeConst = {
  fallbackUserName: 'Guardian',
  headerSubtitle: 'Ready to verify today?',
  badgeIcon: '🛡️',
  badgeTitle: 'Pro Account Active',
  badgeSubtitle: 'Unrestricted High-Precision Scans',
  sectionTitle: 'Verification Modes',
  textModeTitle: 'Text Detection',
  textModeDescription: 'Analyze documents, emails, and articles for AI patterns.',
  textModeIcon: '📄',
  imageModeTitle: 'Image Detection',
  imageModeDescription: 'Identify AI-generated images and deepfake visuals.',
  imageModeIcon: '📷',
  videoModeTitle: 'Video Analysis',
  videoModeDescription: 'Scan videos for synthetic manipulation and deepfakes.',
  videoModeIcon: '🎥',
  newsModeTitle: 'News Verify',
  newsModeDescription: 'Check news credibility and identify bot-generated reports.',
  newsModeIcon: '🌐',
};

export const DetectionConst = {
  textScreenTitle: 'Text Detection',
  textPlaceholder: 'Paste or type content here...',
  charCountSuffix: 'Characters',
  clearButton: 'Clear',
  guidelinesTitle: 'Guidelines',
  textGuidelineOne: '1. Minimum 25 words for accuracy',
  textGuidelineTwo: '2. Avoid overly technical jargon',
  textGuidelineThree: '3. AI models work best on prose',
  analyzeTextButton: 'Analyze Text',
  imageScreenTitle: 'Image Detection',
  uploadIcon: '📷',
  uploadTitle: 'Upload Image',
  uploadSubtitle: 'Supports JGP, PNG, HEIC',
  imageGuidelineOne: '1. Ensure clear resolution',
  imageGuidelineTwo: '2. No heavy filters',
  imageGuidelineThree: '3. Maximum size 10MB',
  startAiScanButton: 'Start AI Scan',
};

export const StatusConst = {
  scanningPrefix: 'Scanning',
  scanningSuffix: '...',
  scanningSubtitle: 'AI pattern matching in progress',
  confidenceLabel: 'Confidence',
  confidenceValue: 'High',
  securityLabel: 'Security',
  securityValue: 'V3.2',
};

export const DashboardConst = {
  appTitle: 'AI Detector',
  guestUser: 'Guest',
  inputLabel: 'Paste text to analyze',
  inputPlaceholder: 'Enter or paste the text you want to check...',
  characterCountSuffix: 'characters',
  analyzingButton: 'Analyzing...',
  analyzeButton: 'Analyze Text',
  clearButton: 'Clear',
  contentSuffix: 'Content',
  confidenceSuffix: 'Confidence',
  aiGeneratedLabel: 'AI Generated',
  humanWrittenLabel: 'Human Written',
  recentAnalysesTitle: 'Recent Analyses',
};

export const ProfileConst = {
  logoutAlertTitle: 'Logout',
  logoutAlertMessage: 'Are you sure you want to logout?',
  cancelButton: 'Cancel',
  logoutButton: 'Logout',
  title: 'Profile',
  fallbackName: 'AIDetector Guardian',
  fallbackEmail: 'guardian@aidetect.io',
  proAccountLabel: '✨ PRO ACCOUNT',
  totalScansValue: '128',
  totalScansLabel: 'Total Scans',
  accuracyValue: '99.2%',
  accuracyLabel: 'Accuracy',
  signOutButton: 'Sign Out',
  version: 'Version 2.4.0 (Emerald Cipher)',
  menuItems: [
    { label: 'Edit Profile', icon: '👤' },
    { label: 'Security Settings', icon: '🔒' },
    { label: 'Detection History', icon: '📜' },
    { label: 'Support Center', icon: '🎧' },
  ],
};

export const SettingsConst = {
  exportDataTitle: 'Export Data',
  exportDataMessage: 'CSV export will be available soon!',
  clearHistoryTitle: 'Clear History',
  clearHistoryMessage: 'History cleared!',
  title: 'Settings',
  notificationsSection: 'Notifications',
  pushNotificationsTitle: 'Push Notifications',
  pushNotificationsSubtitle: 'Receive alerts for analysis completion',
  dataSection: 'Data',
  exportHistoryTitle: 'Export History',
  exportHistorySubtitle: 'Download your analysis history as CSV',
  clearHistoryRowTitle: 'Clear History',
  clearHistoryRowSubtitle: 'Delete all past analyses',
  aboutSection: 'About',
  versionLabel: 'Version',
  versionValue: '1.0.0',
  madeWithLabel: 'Made with',
  madeWithValue: '❤️ AI Detector',
};

export const SplashConst = {
  appName: 'AIDetect',
  tagline: 'Secure. Verify. Protect.',
  bootText: 'INITIALIZING NEURAL CORE',
};

export const ApiConst = {
  noInternetConnection: 'No internet connection',
};
