export const CommonConst = {
  nextArrow: '›',
  unknownUserInitial: 'U',
};

export const AuthConst = {
  loginTitle: 'Sign In',
  loginSubtitle: 'High-precision AI network',
  /** Figma 4311:2 — login hero + form chrome */
  dividerOrEmail: 'OR CONTINUE WITH EMAIL',
  emailLabelUpper: 'EMAIL ADDRESS',
  passwordLabelUpper: 'PASSWORD',
  loginEmailPlaceholder: 'name@company.com',
  signupTitle: 'Sign Up',
  signupSubtitle: 'High-precision network',
  /** Figma 4311:154 — Sign up */
  signupHeroTitle: 'Create Account',
  signupHeroSubtitleLine1: 'Join the high-precision network of',
  signupHeroSubtitleLine2: 'synthetic media verification.',
  signupNamePlaceholderFigma: 'Johnathan Doe',
  signupEmailPlaceholderFigma: 'verify@aidetect.io',
  signupPhonePlaceholder: '+1 (555) 000-0000',
  fullNameLabelUpper: 'FULL NAME',
  signupEmailLabelUpper: 'EMAIL ADDRESS',
  signupPasswordLabelUpper: 'PASSWORD',
  phoneLabelUpper: 'PHONE NUMBER',
  dividerOrContinueWith: 'OR CONTINUE WITH',
  signupLegalLine1: 'By signing up, you agree to our',
  termsOfService: 'Terms of Service',
  signupLegalAnd: ' and ',
  privacyPolicy: 'Privacy Policy',
  signupLegalSuffix: '.',
  footerSignatureLine: 'SECURE. AUTHENTIC. PROTECTED.',
  brandHeaderTitle: 'AIDetect',
  brandHeaderSignIn: 'Sign In',
  legalPlaceholderTitle: 'Notice',
  legalPlaceholderMessage: 'This content will be available in a future update.',
  webViewTermsTitle: 'Terms of Service',
  webViewPrivacyTitle: 'Privacy Policy',
  phoneAuthTitle: 'Phone sign-in',
  phoneAuthHeadline: 'Enter your number',
  phoneAuthSubtitle: 'We will send a verification code by SMS.',
  phoneAuthCta: 'Send code',
  phoneRequiredError: 'Please enter your phone number with country code.',
  /** In-app WebView allowlist uses `src/utils/legalUrls`. */
  termsUrl: 'https://aidetect.in/terms',
  privacyUrl: 'https://aidetect.in/privacy',
  continueWithGoogle: 'Continue with Google',
  signingInWithGoogle: 'Signing in…',
  dividerOr: 'OR',
  emailLabel: 'Email Address',
  emailPlaceholder: 'Enter your email',
  passwordLabel: 'Password',
  passwordPlaceholder: '••••••••',
  signInButton: 'Sign In',
  signUpButton: 'Sign Up',
  loginFooterPrefix: "Don't have an account? ",
  loginFooterCta: 'Create an account',
  signupNameLabel: 'Full Name',
  signupNamePlaceholder: 'Enter your name',
  signupFooterPrefix: 'Already have an account? ',
  signupFooterCta: 'Sign In',
  verifyOtpTitle: 'Verify OTP',
  verifyOtpSubtitle: "We've sent a code to",
  verifyOtpButton: 'Verify Code',
  otpResendPrefix: "Didn't receive code? ",
  otpResendCta: 'Resend now',
  otpResending: 'Sending…',
  otpResentMessage: 'A new verification code has been sent.',
  otpIncompleteError: 'Please enter the full 6-digit code.',
  otpVerifyingMessage: 'Verifying…',
  loginFailedTitle: 'Login Failed',
  tryAgainMessage: 'Please try again.',
  resetEmailRequired: 'Enter your email to reset password',
  resetEmailSentTitle: 'Email Sent',
  resetEmailSentMessage: 'Check your inbox for password reset instructions.',
  genericErrorTitle: 'Error',
  resetEmailFailedMessage: 'Failed to send reset email.',
  signupFailedTitle: 'Signup Failed',
  emailRequiredError: 'Email is required',
  validEmailError: 'Please enter a valid email',
  passwordRequiredError: 'Password is required',
  passwordMinLengthError: 'Password must be at least 6 characters',
  fullNameRequiredError: 'Full name is required',
  passwordUppercaseError: 'Password must contain at least one uppercase letter',
  passwordNumberError: 'Password must contain at least one number',
  verifyEmailTitle: 'Verify your email',
  verifyEmailSubtitle:
    'We sent a verification link to your inbox. Open the link, then return here and continue.',
  verifyEmailAddressLabel: 'Sent to',
  verifyEmailResendButton: 'Resend email',
  verifyEmailResending: 'Sending…',
  verifyEmailResentTitle: 'Email sent',
  verifyEmailResentBody: 'Check your inbox for a new verification link.',
  verifyEmailContinueButton: 'I have verified — continue',
  verifyEmailChecking: 'Checking…',
  verifyEmailStillUnverified:
    'Your email is not verified yet. Open the link we sent you, then try again.',
  verifyEmailSignOutButton: 'Use a different account',
};

export const HomeConst = {
  fallbackUserName: 'Guardian',
  headerSubtitle: 'Ready to verify today?',
  badgeIcon: '🛡️',
  badgeTitle: 'Pro Account Active',
  badgeSubtitle: 'Unrestricted High-Precision Scans',
  sectionTitle: 'Verification Modes',
  textModeTitle: 'Text Detection',
  textModeDescription:
    'Analyze documents, emails, and articles for AI patterns.',
  textModeIcon: '📄',
  imageModeTitle: 'Image Detection',
  imageModeDescription: 'Identify AI-generated images and deepfake visuals.',
  imageModeIcon: '📷',
  videoModeTitle: 'Video Analysis',
  videoModeDescription: 'Scan videos for synthetic manipulation and deepfakes.',
  videoModeIcon: '🎥',
  newsModeTitle: 'News Verify',
  newsModeDescription:
    'Check news credibility and identify bot-generated reports.',
  newsModeIcon: '🌐',
};

export const ComingSoonConst = {
  headline: 'Coming soon',
  message:
    'News credibility checks are not available yet. We will add this in a future update.',
  backButton: 'Go back',
};

export const DetectionConst = {
  textScreenTitle: 'Text Detection',
  textPlaceholder: 'Paste or type content here...',
  charCountSuffix: 'Characters',
  clearButton: 'Clear',
  guidelinesTitle: 'Guidelines',
  textGuidelineOne: '1. Minimum 50 characters for accuracy',
  textGuidelineTwo: '2. Avoid overly technical jargon',
  textGuidelineThree: '3. AI models work best on prose',
  analyzeTextButton: 'Analyze Text',
  textTooShortError: 'Please enter at least 50 characters before scanning.',
  textInvalidTitle: 'Cannot Analyze',
  imageScreenTitle: 'Image Detection',
  uploadIcon: '📷',
  uploadTitle: 'Upload Image',
  uploadSubtitle: 'Supports JPG, PNG, HEIC',
  imageGuidelineOne: '1. Ensure clear resolution',
  imageGuidelineTwo: '2. No heavy filters',
  imageGuidelineThree: '3. Maximum size 10MB',
  startAiScanButton: 'Start AI Scan',
  selectImageButton: 'Select Image',
  changeImageButton: 'Change Image',
  imageSelectedTitle: 'Image Ready',
  imageSelectedSubtitle: 'Tap "Start AI Scan" to analyze.',
  pickerErrorTitle: 'Could not select media',
  noMediaError: 'Please select an image first.',
  videoScreenTitle: 'Video Detection',
  videoUploadIcon: '🎥',
  videoUploadTitle: 'Select Video',
  videoUploadSubtitle: 'Supports MP4, MOV, WebM (max 20MB)',
  videoReadyTitle: 'Video selected',
  videoPlaceholderHint: 'Preview is not shown for videos.',
  videoSelectedSubtitle: 'Tap "Start AI Scan" to analyze.',
  selectVideoButton: 'Select Video',
  changeVideoButton: 'Change Video',
  noVideoError: 'Please select a video first.',
  videoGuidelineOne: '1. Shorter clips analyze faster and more reliably',
  videoGuidelineTwo: '2. Use the original file when possible',
  videoGuidelineThree: '3. Maximum size 20MB',
};

export const ResultConst = {
  resultTitle: 'Scan Result',
  aiGeneratedLabel: 'AI Generated',
  authenticLabel: 'Authentic',
  scoreLabel: 'AI Score',
  confidenceLabel: 'Confidence',
  reasoningLabel: 'Reasoning',
  artifactsLabel: 'Artifacts',
  noArtifacts: 'No notable artifacts detected.',
  doneButton: 'Done',
  retryButton: 'Try Again',
  errorTitle: 'Analysis Failed',
  genericErrorMessage: 'We could not complete the analysis. Please try again.',
};

export const StatusConst = {
  scanningPrefix: 'Scanning',
  scanningSuffix: '...',
  scanningSubtitle: 'AI pattern matching in progress',
  confidenceLabel: 'Confidence',
  confidenceValue: 'High',
  securityLabel: 'Security',
  securityValue: 'V3.2',
};

export const ProfileConst = {
  logoutAlertTitle: 'Logout',
  logoutAlertMessage: 'Are you sure you want to logout?',
  cancelButton: 'Cancel',
  logoutButton: 'Logout',
  title: 'Profile',
  fallbackName: 'AIDetector Guardian',
  fallbackEmail: 'guardian@aidetect.io',
  proAccountLabel: '✨ PRO ACCOUNT',
  totalScansValue: '128',
  totalScansLabel: 'Total Scans',
  accuracyValue: '99.2%',
  accuracyLabel: 'Accuracy',
  signOutButton: 'Sign Out',
  version: 'Version 2.4.0 (Emerald Cipher)',
  menuItems: [
    { label: 'Edit Profile', icon: '👤' },
    { label: 'Security Settings', icon: '🔒' },
    { label: 'Detection History', icon: '📜' },
    { label: 'Support Center', icon: '🎧' },
  ],
};

export const SettingsConst = {
  exportDataTitle: 'Export Data',
  exportDataMessage: 'CSV export will be available soon!',
  clearHistoryTitle: 'Clear History',
  clearHistoryMessage: 'History cleared!',
  title: 'Settings',
  notificationsSection: 'Notifications',
  pushNotificationsTitle: 'Push Notifications',
  pushNotificationsSubtitle: 'Receive alerts for analysis completion',
  dataSection: 'Data',
  exportHistoryTitle: 'Export History',
  exportHistorySubtitle: 'Download your analysis history as CSV',
  clearHistoryRowTitle: 'Clear History',
  clearHistoryRowSubtitle: 'Delete all past analyses',
  aboutSection: 'About',
  versionLabel: 'Version',
  versionValue: '1.0.0',
  madeWithLabel: 'Made with',
  madeWithValue: '❤️ AI Detector',
};

export const SplashConst = {
  appName: 'AI Detector',
  tagline: 'SECURE. VERIFY. PROTECT.',
  bootText: 'INITIALIZING NEURAL CORE',
  navigationDelayMs: 3000,
};

export const ApiConst = {
  noInternetConnection: 'No internet connection',
};
